#!/bin/sh
cd `dirname $0`/.. || exit 1
CLASSPATH=classes:$CLASSPATH
CLASSPATH=`echo jPOS-template-master-2.1.8-SNAPSHOT.jar lib/*.jar | tr ' ' ':'`:$CLASSPATH
exec java -cp $CLASSPATH bsh.Interpreter $*
